@startuml
participant Activity
participant PhoneWindow
participant PhoneLayoutInflater

participant ApplicationContext as ap
participant Resources
participant AssetManager
participant APK

== 获取资源的流程 ==
[-> ap : fetchResources
activate ap
ap -> Resources : ResourcesID
activate Resources
Resources -> AssetManager : FileName
note right
资源ID和文件名称的对应关系被
打包在Apk中resources.arsc文
件中，所以这个转换的过程同样
需要依赖AssetManager来完成
end note
deactivate Resources
activate AssetManager
ap -> AssetManager : FileName
AssetManager -> APK : open
deactivate ap
deactivate AssetManager

== Inflate过程 ==
[-> Activity : setContentView()
activate Activity

Activity -> PhoneWindow : setContentView()
activate PhoneWindow

alt mContentParent == null
PhoneWindow -> PhoneWindow : installDecor()
else
PhoneWindow -> PhoneWindow : mContentParent.removeAllViews()
end alt
PhoneWindow -> PhoneLayoutInflater : inflate()
activate PhoneLayoutInflater

group 资源查找部分
PhoneLayoutInflater -> Resources : getLayout()
activate Resources

Resources -> Resources : loadXmlResourceParser()
activate Resources

Resources -> Resources : getValue()
note right
getValue 查找资源找出来的结果保存在一个
TypedValue 对象中，因为对于有文件类型的
资源来说，资源ID映射到的都是一个文件名称
，所以这里返回的数据类型应该是string，如
果不是则会抛出一个NoteFound的异常
end note
activate Resources

Resources -> AssetManager : getResourceValue()
activate AssetManager

AssetManager -> AssetManager : TypedValue:loadResourceValue()
activate AssetManager

AssetManager --> AssetManager : index of StringBlack
deactivate AssetManager
note right
在这里返回一个索引值用来确定在哪一个资源索引表中
可以获取到ID对应的资源，获取字符串代码如下：
outValue.string = mStringBlocks[index].get(outValue.data)
end note

AssetManager --> Resources : Bool:found
deactivate AssetManager

alt found == ture
Resources -> Resources : return the TypedValue
else
Resources -> Resources : throw NotFoundException
end alt
deactivate Resources

alt value.type == TypedValue.TYPE_STRING
Resources -> Resources : loadXmlResourceParser()
else
Resources -> Resources : throw NotFoundException
end alt


Resources --> PhoneLayoutInflater : XmlResourceParser
deactivate Resources
end group

PhoneLayoutInflater -> PhoneLayoutInflater : inflate()

@enduml
