@startuml

actor Context as ctx

left to right direction
ctx --> (resource) : getResource()
note left
mResource = mPackageInfo.getResource(mMainThread);
每个应用只有一个pakcageinfo
end note
ctx --> (asset) : getAsset()
ctx --> (PackageManager) : getPackageManager()
ctx --> (ApplicationContext) : getApplicationContext()
ctx --> (ContentResolver) : getContentResolver()
ctx --> (AttributeSet) : obtainStyledAttributes()

(SystemService) <-- ctx : getSystemService()
(Broadcast) <-- ctx : sendBraodcast()
(Activity) <-- ctx : startActivity()
@enduml
